# Use node as base image
FROM node:alpine

# Set working directory
WORKDIR /app

# Copy package.json and install dependencies
COPY package*.json ./
RUN npm install

# Copy remaining source code
COPY . .

# Expose port 3000
EXPOSE 3000

# Command to start the server
CMD ["node", "server.js"]
